### ISSUE TITLE
Attempts to read .bin files

### ISSUE THREAD

**Issue by WCAKeith** [authorblues/bizhawk-shuffler-2#1]
It seems if .cue and .bin files are in the "games" folder and you start the script, the bin files will not be filtered out and BizHawk will attempt to open them.

I'm running this on version 2.6.1 of BizHawk.

**Comment by authorblues** [comment]
Can you send me .cue file to look at? I filter the .bin files by reading the .cue files, so I just need to see what format isn't working.

**Comment by authorblues** [comment]
Might be an issue with renaming the cue/bin files, which requires editing the text inside the cue sheet. I have looked into it, and I believe I'm handling most cue sheets correctly, even the more oddly formatted ones. Will reopen if this is still an issue.

If this is still a bug, please attach a cue sheet for me to inspect.
