### ISSUE TITLE
Game complete hotkey doesn't seem to work.

### ISSUE THREAD

**Issue by nameless01234567** [authorblues/bizhawk-shuffler-2#10]
No matter how long I wait, pressing the hotkeys won't send the games to the completed games list.

**Comment by authorblues** [comment]
Just to be sure, did you make sure the Bizhawk window was the active window when you pressed the hotkey (or do you have Bizhawk set to accept background input from more than just controller)? If you could confirm that for me, I'll see what I can do.

**Comment by nameless01234567** [comment]
Yes, I'm never with the Bizhawk window not active, and even then I set it to accept background input and even then it doesn't work.

**Comment by authorblues** [comment]
If you are able, try the latest version with the additional non-chord hotkeys option (Backslash or RightCtrl). If those work, that narrows down the potential problem.

**Comment by nameless01234567** [comment]
I discovered the problem, my notebook doesn't have a right control, and that is the one needed, it also doesn't have a End, so it works only with alt+shift+d or alt+shift+delete.

Sorry for not having tested those.
