### ISSUE TITLE
Z3R Solo Multi-World Plug-In: Items received multiple times

### ISSUE THREAD

**Issue by arsmith** [authorblues/bizhawk-shuffler-2#14]
When playing the Z3R Solo Multi-World Plug-In, some items were sent once and received multiple times, including on multiple different shuffles to that particular rom.  The very first chest I opened as player 1 had 50 rupees for player 2.  When player 2 started gameplay, they received the rupees twice.  Immediately afterwards, P2 found 10 arrows for P1, and then a bit later an armor upgrade; when gameplay switched back to P1, P1 received that bundle of 10 arrows 14 times, and did not receive the armor.  When gameplay switched to P2 again, P2 received 12 more packs of 50 rupees, despite P1 having not picked up any items at all while playing.  That's about where I gave up.

I was using the Bizhawk Shuffler commit from August 2nd, the most recent commit at time of reporting.

Z3R Software Info:
Overworld Randomizer 0.1.7.2 (based on Door Randomizer 0.5.0.1).
GitHub link: [Overworld Randomizer](https://github.com/codemann8/ALttPDoorRandomizer)

I know this isn't the Door Randomizer, but it's based off of it, and the latest pull from the Door Randomizer branch was relatively recent, so I thought this should work. If it's just something unsupported, that's fine, just let me know.

Roms, adjusted roms, multidata, and spoiler attached.  I used the two adjusted roms when actually playing.

[OR_940102655.zip](https://github.com/authorblues/bizhawk-shuffler-2/files/6928199/OR_940102655.zip)

Here's the video from the stream when this happened.  I started it a bit early, because there was a noticeable stutter in BizHawk before I started playing, in case that's relevant.  Game play starts at around 1:45.  First sign of something unusual is around 3:00.
[Video Link](https://www.twitch.tv/videos/1107493504)

**Comment by authorblues** [comment]
I will admit that I tested this very quickly because overworld shuffling makes it way harder for me to find more items to send, but 1) I know this change won't break the standard door randomizer (which I suspect actually might have been broken based on this bug as well), and 2) if it is still broken, I will reopen this issue and continue looking for a fix.

My fix was very simple however. Hoping it is sufficient.
