### ISSUE TITLE
Z3 Item Retention?

### ISSUE THREAD

**Issue by MeleeWizard** [authorblues/bizhawk-shuffler-2#20]
Just tried Z3 solo multiworld, and when I Save & Quit, all that seed's items disappear, including rupees and ammo.

**Comment by authorblues** [comment]
I can't seem to reproduce this issue. If you could provide more information, that might help.

1. Did you use Aerinon's Z3R multiworld randomizer? Were there any unusual settings?
2. If you could attach any generated roms for me to inspect to a comment, that would help.
3. What were your settings on the shuffler? Attaching your `config.lua` file from the shuffler-src/ folder would give me a better picture of what your configuration is.
4. Could you give me instructions for how to reproduce the issue (what steps I would need to take to reproduce, what you expected to happen, what actually happened instead).

The roms I have tested with seemed to have no issues with Save & Quit.

**Comment by MeleeWizard** [comment]
I am using Aerinon's multiworld.  Roms, along with my settings for both the randomizer and the shuffler are included.  Quickest item locations to replicate this are sanctuary chest in seeds 1 and 2 and Link's house in seed 3.  I collect the item, S&Q, and when I start back up (I'm not resetting the emulator), the item is gone, but the chest is still open.
[Troubleshooting.zip](https://github.com/authorblues/bizhawk-shuffler-2/files/6970059/Troubleshooting.zip)
