### ISSUE TITLE
Shuffler always turns sound on

### ISSUE THREAD

**Issue by kalimag** [authorblues/bizhawk-shuffler-2#23]
https://github.com/authorblues/bizhawk-shuffler-2/blob/410b33a2fb12d99a116f4685e3f25e29b6499a42/shuffler.lua#L503

This line always enables the sound even if it was disabled (`false or true == true`). I assume this is intended to supply a default value if  `config.sound` is  `nil`, which could be expressed as `config.sound ~= false`.

I think it would be preferable if the shuffler just didn't call `client.SetSoundOn` if `config.sound` is `nil`, so it doesn't unmute Bizhawk if it was muted before the shuffler was started.

**Comment by authorblues** [comment]
Haha, what a silly oversight. You're obviously correct. Easy fix.
