### ISSUE TITLE
Z3R Solo-Multiworld Progressive Item Bugs

### ISSUE THREAD

**Issue by arsmith** [authorblues/bizhawk-shuffler-2#37]
**Describe the bug**
This might actually be two bugs, but given they both involve Progressive Bows in Z3R, they might be related.
1. P1 found both progressive bows for P2 in the same shuffle; when the shuffler returned to P2, they received two L1 bows, effectively locking them out of ever receiving a L2 bow.
2. Later in the same seed, P2 found the first progressive bow for P1.  When P1 received it, they received an L2 bow, eliminating the need for P1's second progressive bow.
3. Later still in the same seed, P2 found P1's second progressive bow; nothing unexpected happened here, but it does confirm that P1 wasn't supposed to have both bows.

**To Reproduce**
1. In the attached seed, play as normal until P1 has access to East Side Dark Death Mountain.
2. As P1 enter the shop at the bottom of East Side Dark Death Mountain and purchase the Progressive Bow for sale.  It should send to P2.
3. Before gameplay returns to P2, enter the cave next to the shop (i.e. Superbunny Cave), and collect the two items in chests from that cave, one of which should be a Progressive Bow that sends to P2.
4. Let gameplay return to P2.
5. Observe that P2 receives 2 L1 bows, when they should receive an L1 and an L2 bow.
6. If you want to investigate further, continue until P2 has Boots.
7. Navigate P2 to Bonk Rocks (the pile of rocks blocking a cave entrance on the ledge by Sanctuary).
8. Clear the rocks and enter the cave to collect a progressive bow for P1.
9. Observe that P1 receives an L2 bow, instead of an L1 bow.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Bizhawk Version: 2.6.2

**Additional context**
Seed was created using version 0.1.9.1 of the Z3R Overworld Shuffler, found here: https://github.com/codemann8/ALttPDoorRandomizer

**Logs**
[Z3R Solo-Multiworld Shuffler Bug Report.zip](https://github.com/authorblues/bizhawk-shuffler-2/files/7117433/Z3R.Solo-Multiworld.Shuffler.Bug.Report.zip)

**Screenshots**
Clips from the stream:
1. https://www.twitch.tv/videos/1140888903
2. https://www.twitch.tv/videos/1140888902
3. https://www.twitch.tv/videos/1140888901

If you need any additional information, DM me on Twitter, @Ars_Ignis.

**Comment by authorblues** [comment]
Relevant portion of message log:
```
[22:45:10] [SZ3RM] find x3A for p2 (found by p1)
[22:45:10] [SZ3RM] send x3A for p2 (found by p1) - 0360,e0
[22:45:46] [SZ3RM] find x28 for p2 (found by p1)
[22:45:46] [SZ3RM] send x28 for p2 (found by p1) - 01f0,20
[22:45:49] [SZ3RM] find x3A for p2 (found by p1)
[22:45:49] [SZ3RM] send x3A for p2 (found by p1) - 01f0,10
[22:46:09] [SZ3RM] recv x3A for p2 (sent by p1) - 0360,e0 (38)
[22:46:09] [SZ3RM] recv x28 for p2 (sent by p1) - 01f0,20 (39)
[22:46:10] [SZ3RM] recv x3A for p2 (sent by p1) - 01f0,10 (40)
```

Just a note for me.
