### ISSUE TITLE
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)

### ISSUE THREAD

**Issue by nameless01234567** [authorblues/bizhawk-shuffler-2#47]
After using the shuffler for a while and reseting a couple of times due to unrelated audio issues, this message appeared
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   em NLua.Lua.PanicCallback(IntPtr luaState)
   em lua_error(lua_State* )
   em NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   em NLua.Lua.SetPendingException(Exception e)
   em NLua.LuaMethodWrapper.call(IntPtr luaState)
   em NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   em lua_resume(lua_State* , Int32 )
   em BizHawk.Client.EmuHawk.Win32LuaLibraries.ResumeScript(LuaFile lf)
   em BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass61_1.<ResumeScripts>b__1()
   em BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
then it stopped working.

OS: Windows 10
Bizhawk Version: 2.6.2
[message.log](https://github.com/authorblues/bizhawk-shuffler-2/files/7765834/message.log)
![image](https://user-images.githubusercontent.com/87944920/147168447-3b283c89-32cb-48f4-becd-a6fab413184e.png)

**Comment by nameless01234567** [comment]
Some more information that I discovered yesterday.
The error happens if the core is changed after there is a savestate in a different core. Only solution I can think of is deleting all saves of a specific core if there is ever a need to change it.

**Comment by authorblues** [comment]
Interesting. Savestates from different cores are always going to mutually incompatible, but I wonder if there is some way to easily identify such a mistake. Can probably save core information in the config file to announce the problem before the error happens.

**Comment by nameless01234567** [comment]
I'm aware of that, but glad if this helps somehow.
