### ISSUE TITLE
Allow for Adding/Removal of Games from the UI

### ISSUE THREAD

**Issue by Zombietrain5k** [authorblues/bizhawk-shuffler-2#51]
**Is your feature request related to a problem? Please describe.**
Not really...I have a peculiar use case. I'm currently playing through a 100+ RPG shuffler at 60 minute change overs. 

**Describe the solution you'd like**
Allow for adding and removing games from the UI

**Describe alternatives you've considered**
Unsure on an alternative for this. 

**Additional context**
Nothing to add.

Thanks for your consideration!

**Comment by authorblues** [comment]
While this isn't technically impossible (though a bit annoying to do via a Lua script), I question if just adding/removing roms from the `games/` is not sufficient on its own. The shuffler already handles games being added and removed gracefully, so it would simply be a frontend to copying/pasting the file on the user's behalf. If I'm misunderstanding the idea and why it might be better to do it through the UI, please let me know and I'll reopen this.

**Comment by Zombietrain5k** [comment]
Hey Authorblues! 

Thanks for taking the time to look over my request! 

Sorry I wasn't more clear with my idea. What I was thinking was like a two column UI interface that could pull from a folder (or multiple folders) to populate a "master list" (left column) that you could then select games from to add to the "games" folder (right column). This could also have the functionality of clicking and removing the game from the "games" folder (right column) deleting the gamelist txt, remove any save files, etc... so the shuffler is ready for the next launch. 

This is purely for convenience, the copy/paste and deleting the txt file works fine, but thought I'd throw the idea out there if you guys were looking for enhancements :). Lemme know if you're looking for more clarification and I totally get if this isn't something worth the time for implementation. 

Thanks!
Zombietraine
