### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by Dommi669** [authorblues/bizhawk-shuffler-2#62]
When I load an N64 game (OOT) for example, it always crashes when I reload the core or switch games with Mupen64Plus.  I am using Windows 8.1 and Direct3D9 (but OpenGl works like that too) with the Glide64mk2 video plugin (since that's the only one that shows everything correctly in my PC). Help would be much appreciated. Thanks.

**Comment by Dommi669** [comment]
Also, I've checked the expansion pack option for those roms.

**Comment by kalimag** [comment]
Which version of BizHawk are you using?

By crash, do you mean BizHawk suddenly closes, or is there some kind of error message?

Does this also happen if you don't have the shuffler script loaded?

**Comment by Dommi669** [comment]
I'm using the latest version (2.8), and it happens even if I don't have the shuffler script loaded.

**Comment by kalimag** [comment]
Belatedly closing this because it's unrelated to the shuffler.
