### ISSUE TITLE
Problem shuffling OoT and MM randomizers

### ISSUE THREAD

**Issue by matthewkirby** [authorblues/bizhawk-shuffler-2#7]
Following instructions in FAQ, I am opening up an issue here. I attempted today to run the shuffler with an Ocarina of Time randomizer (ootr) seed and a Majora's Mask randomizer (mmr) seed. My Bizhawk 2.6.2 runs both just fine on their own.

The script starts with the ootr seed and everything works fine. Then it swaps to the mmr seed and it looks good. However when it goes to swap back to the ootr seed, I am just left with a white screen. Eventually, it tries to swap back to mmr and I see mmr but completely frozen. Then it swaps back to the white screen again and so on and so on.

Not super sure what to test or how to proceed. I tried patching different seeds and still see the same problem. I also know some people ran this exact combination a couple of days ago and didn't run into these issues.

**Comment by authorblues** [comment]
Do you have "Use Expansion Slot" enabled in the N64 settings in Bizhawk? I believe that is a known issue for ZOOTR + Bizhawk. If that fixes it, please let me know so I can offer that as part of my FAQ.

**Comment by matthewkirby** [comment]
Oh yeah, sorry I was in a rush and forgot to update this. Yes that was indeed what I did to fix it. It was weird because it looks like it breaks save states but otherwise the game runs fine haha.

**Comment by authorblues** [comment]
Yeah, the only way it seems to break the shuffler is just that it crashes when it tries to rapidly load savestates. Very strange behavior, but I'm glad it was fixed. I'll add this to the FAQ asap, since this isn't an uncommon issue.

**Comment by authorblues** [comment]
Added. https://github.com/authorblues/bizhawk-shuffler-2/wiki/Frequently-Asked-Questions
