### ISSUE TITLE
Castlevania: Symphony of the Night Rando Creates "desktop.ini" Game

### ISSUE THREAD

**Issue by ArrenJevleth** [authorblues/bizhawk-shuffler-2#72]
**Describe the bug**
Whenever I include the files for a randomized version of Castlevania: Symphony of the Night [SotN] (the .cue file and both .bin files, created through sotn.io ) into the /games folder and start the shuffler, it adds a "desktop.ini" game to the .games-list.txt file, and when the shuffler tries to load the "game", it prompts me to select a console it should be assigned to, which then stops the shuffler from functioning because it won't be able to load the next game. There are no issues when I include the non-randomized game files.

**To Reproduce**
1. Create randomized file of SotN per the sotn.io site and procedure (randomizes the Track 1.bin file, needs to be put in same folder as the .cue file)
2. After running shuffler.lua , put the .cue and .bin files into the /games folder per normal setup
3. When the shuffler is started, "desktop.ini" will be included in the 

**Environment (please complete the following information):**
 - OS: Windows 10
 - BizHawk Version: 2.9.1

**Additional context**
I did multiple combinations of randomized and non-randomized games (including A Link to the Past, Super Metroid, Mega Man X, and Super Metroid/Link to the Past Crossover rando (https://github.com/authorblues/bizhawk-shuffler-2/files/15370057/message.log)
) to break it down and confirm that the SotN randomized files were the impetus for this issue. The only parts of the shuffler setup I changed was the time range for when the games would swap.

**Logs**
Please attach `message.log` and `shuffler-src/config.lua`.
[message.log](https://github.com/authorblues/bizhawk-shuffler-2/files/15370060/message.log)
[config.lua.txt](https://github.com/authorblues/bizhawk-shuffler-2/files/15370065/config.lua.txt) (GitHub wouldn't let me upload the config.lua file directly, so I saved a separate copy as a .txt file to upload it)
[.games-list.txt](https://github.com/authorblues/bizhawk-shuffler-2/files/15370076/default.games-list.txt)

**Screenshots**
![BizHawk Loading Desktop-dot-INI](https://github.com/authorblues/bizhawk-shuffler-2/assets/170256860/09e92ac9-2afe-45a2-893a-294a373d821d)

**Comment by kalimag** [comment]
Ultimately you have to make sure that you don't put any non-game files into the games directory. But I've added ini files to the ignore list for convenience.
