### ISSUE TITLE
Solo Z3R Rupee/Heart Container Issue

### ISSUE THREAD

**Issue by MeleeWizard** [authorblues/bizhawk-shuffler-2#8]
When rupees or heart containers are collected that go to another seed, it is treated as if it belongs to the current seed as well.

**Comment by authorblues** [comment]
This was a bug that I had always assumed was on the Z3R multiworld, but after confirming that it isn't with Aerinon, I looked into this a little more and found the issue. Thanks for pushing me to figure out the problem! 👍
