### ISSUE TITLE
Not all games appear.

### ISSUE THREAD

**Issue by nameless01234567** [authorblues/bizhawk-shuffler-2#9]
I have a list with over a 100 games on the games folder, but only 30-40 of them show up. I have already set for shuffler to change very fast to make sure it wasn't just the randomness of the shuffler, but it changed almost 200 times over the same 30 games.

**Comment by authorblues** [comment]
Can you post the contents of the .games-list.txt file that should have been generated in the `games/` folder?

**Comment by nameless01234567** [comment]
[.games-list.txt](https://github.com/authorblues/bizhawk-shuffler-2/files/6874332/default.games-list.txt)
Here it is.

**Comment by authorblues** [comment]
Yeah, I've confirmed this problem locally with large game lists. I will try to get this fixed asap, thanks!

**Comment by nameless01234567** [comment]
No problem.

**Comment by authorblues** [comment]
I'm uncertain whether this fix is 100% correct, but the PRNG seed was looping with such a naive method, so I've added a small offset that seems to be fixing the problem. You're still subject to [the coupon collector problem](https://en.wikipedia.org/wiki/Coupon_collector%27s_problem), so huge lists are still going to have games that don't show up for an absurdly long time.

**Comment by nameless01234567** [comment]
Yeah, but that's part of what I subjected myself to, I'm fine with that. The problem was only such a low amount of games appearing from such a large list, if 80-90 games have appeared and the rest doesn't show up, that's expected.
